### ISSUE TITLE
Transparent areas

### ISSUE THREAD

**Issue by Grimlex** [spinico/CustomWindow#1]
I noticed an issue when testing your window on my virtual machine. When clicking on the icon, the area of the System Menu is displayed transparently for a short period of time.
![window2](https://cloud.githubusercontent.com/assets/25812672/25120303/c68e310e-241d-11e7-8cd3-ae83d0a2c004.gif)

Another custom chrome window and the standard Windows window does not reproduce this issue, so I'm pretty sure it can only be caused by your custom window.
![window3](https://cloud.githubusercontent.com/assets/25812672/25120497/9d2f60de-241e-11e7-8ca9-defa6fd5be38.gif)  ![window1](https://cloud.githubusercontent.com/assets/25812672/25120502/a1d09dba-241e-11e7-8d13-39fe52a72b80.gif)

I can only reproduce this issue on my virtual machine , which is virtualized with VMware Workstation 12 Player (It's quite slow at the moment). When browsing your source code, I couldn't find a suspicious line which could cause the issue. Do you have an idea what I could do to prevent these transparent areas?

**Comment by spinico** [comment]
I could not reproduce this issue on my end (Windows 7): my window system popup use the fade instead of the slide animation. What OS is your VM running on? Does your VM has desktop composition enabled?
 Did you try it on a faster machine to see if the issue still occured? 

My guess would be the way the slide animation and transparency works on a  window with the layered style active (which is the case on this project). You may try to disable it to see if it changes the observed behavior ([setting AllowsTransparency to false](https://github.com/spinico/CustomWindow/blob/9e913159f075a30f97a3a4bf95d992055f426ef8/CustomChrome.cs#L479)). 

Nonetheless, I still managed to update the system popup to a simpler form using window messaging instead of the TrackPopupMenuEx call. It might help with the issue. 

I like the animated gif to demonstrate the issue, how or what did you use to produce them?
